# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b89020bda1b57ab710111ce313e4c05bf1ae63edcfca02ca8d2709970b984b20a5b8dfa28307b0b3fe4f8eaaf53f2fd847fcc68be2bf04702849328b256c9cee

test:
  secret_key_base: a0911fc8891154c9730b4084cfcb8a01b12c6c3a869de2269d6805c6cb2b57a8ecffa6c313f129d31500dfe280c17a82bb78e4e5457a8a80fcb586464d2f3d35

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
