# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e383e1e816aeca8fc34489933cbe224f18ca229a8c7b8454e7bbc6c1fbcfc20ba14fe3d5f9ed8408b1b1b589af595a23b8a1b26ab155339348e7be37f4182c60

test:
  secret_key_base: ddea7146f38428b8a3f81f662aee6ea5b0c23759b5924f9fd38bbdd6b6287aa70002339813ff49f0bdd34f791aeca8e3aad8ce54daed39bac54adb6726e010d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
